name: 'q1'

on: [workflow_dispatch]

#permissions:
#  contents: read

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List folder
        run: |
          cd Q1
          ls -al
     
      - name: Run answer A
        run: ./a.sh
        working-directory: ./Q1
      
      - name: Run answer B
        run: ./b.sh
        working-directory: ./Q1
        
      - name: Run answer C
        run: ./c.sh
        working-directory: ./Q1


      
